---

- name: Run show commands on routers
  hosts: cisco_routers

  tasks:
    - name: Collect facts
      ios_facts:
        gather_subset:
          - "!hardware"

    - name: run sh ip int br
      ios_command:
        commands: show ip int br
      register: sh_ip_int_br_result

    - name: Set interfaces fact
      set_fact:
        all_interfaces: "{{ sh_ip_int_br_result.stdout[0] | regex_findall('(\\S+) +([\\d.]+) +') }}"

    - name: Generate template
      template:
        src: templates/sh_ip_int_br_ios_command.j2
        dest: csv_parts/{{ansible_net_hostname}}_result.csv

    - name: Write all files to CSV
      assemble:
        src: csv_parts/
        dest: final_result.csv
      run_once: true

    - name: Remove csv_parts file
      file:
        path: csv_parts/{{ansible_net_hostname}}_result.csv
        state: absent

